# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/RootDesign/RootDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign || ORIG_REF_NAME==RootDesign} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_processing_system7_0_0/RootDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_processing_system7_0_0 || ORIG_REF_NAME==RootDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_SimpleFilter_0_0/RootDesign_SimpleFilter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_SimpleFilter_0_0 || ORIG_REF_NAME==RootDesign_SimpleFilter_0_0} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_axi_dma_0_0/RootDesign_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_axi_dma_0_0 || ORIG_REF_NAME==RootDesign_axi_dma_0_0} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_xbar_0/RootDesign_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_xbar_0 || ORIG_REF_NAME==RootDesign_xbar_0} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_ps7_0_axi_periph_0/RootDesign_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==RootDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_rst_ps7_0_100M_0/RootDesign_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==RootDesign_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_xbar_1/RootDesign_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_xbar_1 || ORIG_REF_NAME==RootDesign_xbar_1} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_axi_mem_intercon_0/RootDesign_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_axi_mem_intercon_0 || ORIG_REF_NAME==RootDesign_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_auto_pc_0/RootDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_auto_pc_0 || ORIG_REF_NAME==RootDesign_auto_pc_0} -quiet] -quiet

# IP: bd/RootDesign/ip/RootDesign_auto_pc_1/RootDesign_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RootDesign_auto_pc_1 || ORIG_REF_NAME==RootDesign_auto_pc_1} -quiet] -quiet

# XDC: bd/RootDesign/RootDesign_ooc.xdc
