# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zapma/PiRadioInterview/InterviewProject/InterviewProject.srcs/sources_1/bd/RootDesign/ip/RootDesign_xbar_1/RootDesign_xbar_1.xci
# IP: The module: 'RootDesign_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zapma/PiRadioInterview/InterviewProject/InterviewProject.srcs/sources_1/bd/RootDesign/ip/RootDesign_xbar_1/RootDesign_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RootDesign_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/zapma/PiRadioInterview/InterviewProject/InterviewProject.srcs/sources_1/bd/RootDesign/ip/RootDesign_xbar_1/RootDesign_xbar_1.xci
# IP: The module: 'RootDesign_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zapma/PiRadioInterview/InterviewProject/InterviewProject.srcs/sources_1/bd/RootDesign/ip/RootDesign_xbar_1/RootDesign_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RootDesign_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
